### ISSUE TITLE
List of Objects Doesn't Add Closing Bracket to Objects When Calling JsonAsty.unparse()

### ISSUE THREAD

**Issue by tylerpashigian** [rse/json-asty#1]
I am running into an issue when using this with a list of objects. For example, I have changed the sample JSON object from the repo/npm page to this (changed foo to a list of objects):

`{
    "foo": [
      {
          "bar": true,
          "baz": 42.0,
          "quux": [ "test1\\"test2", "test3", 7, true ]
      },
      {
          "bar": true,
          "baz": 42.0,
          "quux": [ "test1\\"test2", "test3", 7, true ]
      }  
    ]
}`

Everything works correct in terms of reading the JSON and creating the AST, but when unparsing the AST back to JSON, the list of objects looks like this: 

`{
    "foo": [
      {
          "bar": true,
          "baz": 42.0,
          "quux": [ "test1\\"test2", "test3", 7, true ]
      ,
      {
          "bar": true,
          "baz": 42.0,
          "quux": [ "test1\\"test2", "test3", 7, true ]
      }  
    ]
}`

I think the reason for this is when creating the AST, the epilog for the first object is being set to "," and it is ignoring the closing bracket when unparsing, whereas the epilog for the last object in the list, the epilog is being set to "}" and being unparsed correctly. Is this a bug or am I using the library wrong? Thanks in advanced!

**Comment by igor-lemon** [comment]
+1 I have the same issue

**Comment by Eddman** [comment]
I've fixed that issue and created a PR #3. Also if you don't want to wait for merge it is deployed as [@netocny/json-asty](https://www.npmjs.com/package/@netocny/json-asty)

**Comment by caraya** [comment]
@Eddman if you promote your own fork, at least make sure we can ask questions in the fork rather than having to do it here... 

Does your fork work when importing ESM modules?

**Comment by rse** [comment]
These problems were fixed by taking over the proposed fixes. We can already close this issue, I think.
