### ISSUE TITLE
Cannot find module 'asty' when imported in create-react-app project

### ISSUE THREAD

**Issue by stanislawosinski** [rse/json-asty#2]
Excellent library! I'd like to use it in my project based on create-react-app, but I'm getting the `Cannot find module 'asty'` message.

Steps to reproduce:

1. `npx create-react-app json-asty-cra`
2. In `json-asty-cra` directory, edit package.json to add the `"json-asty": "1.0.5"` dependency. 
3. In `src/App.js`, add `import JsonAsty from "json-asty";`
4. Start development server: `npm start`.
5. Open http://localhost:3000. You will get the `Cannot find module 'asty'` message.
6. After `npm build`, the same error appears when running the production build.

Any ideas how to resolve this? I'd really like to use json-asty, it would make things so much easier in my code.

**Comment by caraya** [comment]
I'm experiencing the same issue when trying to import the package to a project using ESM modules

I don't think this package has ESM modules exports, therefore it can't be imported to ESM packages. 

Did you come up with an alternative?

**Comment by stanislawosinski** [comment]
I used a different library: https://github.com/vtrushin/json-to-ast.
